[package]
name = "leanr-rag-gateway"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
leanr-core = { path = "../leanr-core" }

[dev-dependencies]
